import { USE_MOCK_API, API_URL } from '../../config';

export const API_BASE_URL = API_URL;

export const API_ENDPOINTS = {
  LOGIN: 'Admin/AdminLogin',
  ADD_ADMIN: 'Admin/AddAdmin',
  GET_ADMINS: 'Admin/GetAllAdmins',
  DELETE_ADMIN: (id) => `Admin/DeleteAdmin/${id}`,
  DASHBOARD: 'Dashboard/GetDashboardData',
  UPDATE_DOLLAR_RATE: 'Dashboard/UpdateDollarRate',
  GET_SUPPLIERS: 'Supplier/GetSuppliersRecord',
  ADD_SUPPLIER: 'Supplier/AddSupplier',
  GET_CUSTOMERS: 'Customer/GetCustomersRecord',
  ADD_CUSTOMER: 'Customer/AddCustomer',
  GET_BANKS: 'Bank/GetBanksRecord',
  ADD_BANK: 'Bank/AddBankRecord',
  GET_PAYMENTS: 'Payment/GetPaymentsRecord',
  ADD_PAYMENT: 'Payment/AddPaymentRecord',
  GET_BANK_BY_NAME: (bankName) => `Bank/GetBanksRecordByName?bankName=${bankName}`,
  GET_PENDING_REGISTRATION: 'Admin/PendingRegistrations',
  REGISTRATION_ACTION: 'Admin/ChangeUserStatus',
  DELETE_USER: (id) => `Admin/DeleteUser/${id}`,
  GET_APPROVE_CUSTOMERS: 'Admin/ApprovedUsers',
  GET_REJECTED_CUSTOMERS: 'Admin/RejectedUsers',
  GET_PENDING_TRANSFER: 'Admin/GetPendingTransfer',
  GET_APPROVED_TRANSFER: 'Admin/GetApprovedTransfer',
  APPROVE_TRANSFER: 'Admin/ConfirmTransfer',
  APPROVE_THIRD_PARTY_TRANSFER: (id) => `Admin/CompleteThirdPartyTransfer?id=${id}`,
  DELETE_SUPPLIER: (id) => `Supplier/DeleteSupplier/${id}`,
  DELETE_CUSTOMER: (id) => `Customer/DeleteCustomer/${id}`,
  DELETE_PAYMENT: (id) => `Payment/DeletePayment/${id}`,
  DELETE_BANK: (id) => `Bank/DeleteBank/${id}`,
  ADD_COMPANY_ACCOUNTS: 'Dashboard/AddCompanyAccount',
  ADD_COMPANY_NUMBERS: 'Dashboard/AddCompanyPhoneNumbers',
  COMPLETE_CUSTOMER_PAYMENT: 'Customer/CompleteCustomerPayment',
  DELETE_COMPANY_ACCOUNT: (id) => `Dashboard/DeleteAccount/${id}`,
};